version: '3'

services:
  vvveb:
    container_name: "php8"
    build: .
    ports:
      - 8080:80
    volumes:
      - type: bind
        source: C:\Users\makot\repos\docker-vvveb-demo\app
        target: /var/www/html
    tty: true
    privileged: true
    depends_on:
      - db
    networks:
      - mysql-networks
      - default
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vvveb
      MYSQL_USER: vvveb
      MYSQL_PASSWORD: vvveb
      TZ: "Asia/Tokyo"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
    tty: true
    networks:
      - mysql-networks
      - default

networks:
  mysql-networks:
    external: true
