
CREATE TABLE IF NOT EXISTS `message` (
`message_id` INTEGER PRIMARY KEY AUTOINCREMENT,
`type` TEXT NOT NULL DEFAULT 'publish',
`data` TEXT NOT NULL DEFAULT '',
`meta` TEXT NOT NULL DEFAULT '',
`date_added` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
`date_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP
-- PRIMARY KEY (`post_id`)
);
